# Generated by Django 3.0.4 on 2020-03-27 17:03

import django.core.validators
from django.db import migrations, models
import micro.image_paths
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='Egypt', max_length=100)),
                ('city', models.CharField(choices=[('mt', 'Matruh'), ('al', 'Alexandria'), ('bh', 'Beheira'), ('ks', 'Kafr El Sheikh'), ('dk', 'Dakahlia'), ('da', 'Damietta'), ('ps', 'Port Said'), ('ns', 'North Sinai'), ('gr', 'Gharbia'), ('mo', 'Monufia'), ('qa', 'Qalyubia'), ('sh', 'Sharqia'), ('is', 'Ismailia'), ('gi', 'Giza'), ('fa', 'Faiyum'), ('ca', 'Cairo'), ('su', 'Suez'), ('ss', 'South Sinai'), ('bs', 'Beni Suef'), ('mi', 'Minya'), ('wa', 'El Wadi El Gedid'), ('as', 'Asyut'), ('rs', 'Red Sea'), ('so', 'Sohag'), ('qn', 'Qena'), ('lx', 'Luxor'), ('sw', 'Aswan')], default='ca', max_length=2)),
                ('building_number', models.IntegerField(default=0)),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=micro.image_paths.profile_image_path)),
                ('about', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A phone number already exists.'}, max_length=128, null=True, region=None, unique=True)),
                ('transportation', models.CharField(blank=True, choices=[('b', 'Bicycle'), ('m', 'Motorcycle'), ('c', 'Car'), ('v', 'Van'), ('t', 'Truck')], max_length=1, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other Gender')], max_length=1, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(14)])),
                ('accept_terms', models.BooleanField(default=False)),
                ('is_tasker', models.BooleanField(default=False)),
                ('addresses', models.ManyToManyField(related_name='addresses', to='micro_profile.Address')),
            ],
        ),
    ]
