# Generated by Django 3.0.4 on 2020-04-01 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_taskdeal_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasker', to=settings.AUTH_USER_MODEL),
        ),
    ]
